# =============================================================================
# Kustomize Base — kustomization.yaml
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backstage-deployment.yaml

namespace: idp-dev

commonLabels:
  app.kubernetes.io/part-of: developer-portal
  app.kubernetes.io/managed-by: kustomize

patchesStrategicMerge: []

configMapGenerator:
  - name: backstage-config
    literals:
      - NODE_ENV=production
      - PORT=7007
      - BACKSTAGE_BASE_URL=http://localhost:7007
